name: Deploy Sage Theme to Hostinger

on:
  push:
    branches:
      - main  # deploys when you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.28.100
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /domains/heygirlsbkk.com/public_html/wp-content/themes/heygirlsbkk/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/.env
            **/package.json
            **/package-lock.json
            **/composer.json
            **/composer.lock
            **/vite.config.js
            **/webpack.mix.js
            **/tailwind.config.js
            **/postcss.config.js
            **/.DS_Store
            **/Thumbs.db
            **/npm-debug.log
            **/yarn-error.log
            **/README.md
            **/LICENSE.md
