name: Deploy Sage Theme to Hostinger

on:
  push:
    branches:
      - main  # deploys on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.heygirlsbkk.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          # The local folder you want to upload (this whole theme folder)
          local-dir: ./
          # The target directory on your Hostinger install:
          server-dir: /public_html/wp-content/themes/heygirlsbkk/
          # Optional safety flags:
          exclude: |
            **/.git*
            **/.github*
            node_modules/**
            vendor/**
