name: Deploy Sage Theme to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy via SFTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: sftp://145.79.28.100
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-dir: ./
          server-dir: /domains/heygirlsbkk.com/public_html/wp-content/themes/heygirlsbkk/
          state-name: .ftp-deploy-sync-state.json
          timeout: 120000
          exclude: |
            **/.git*
            **/.github*
            node_modules/**
            tests/**
            storage/**
            .env
            .DS_Store
            Thumbs.db
            npm-debug.log
            yarn-error.log
            README.md
            LICENSE*
            composer.json
            package.json
            package-lock.json
            vite.config.js
            postcss.config.js
            tailwind.config.js
            webpack.mix.js
