name: Deploy Sage Theme to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build for production
        run: npm run build

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.28.100
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: explicit
          passive: true
          local-dir: ./
          server-dir: /domains/heygirlsbkk.com/public_html/wp-content/themes/heygirlsbkk/
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.env
            **/package*.json
            **/composer*.json
            **/webpack.mix.js
            **/tailwind.config.js
            **/postcss.config.js
            **/vite.config.js
            **/public/.vite/**
            **/public/hot
            **/.DS_Store
            **/Thumbs.db
            **/npm-debug.log
            **/yarn-error.log
            **/README.md
            **/LICENSE*
